management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    
  metrics:
    export:
      prometheus:
        enabled: true
spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
logging:
  level:
    root: INFO
host_id: testhost
service_id: testservice